### ISSUE TITLE
Data Binding SelectedItems Property of a ListBox

### ISSUE THREAD

**Issue by neemanejad** [HydrologicEngineeringCenter/DSSExcel#1]
I'm trying to use data binding to bind the `SelectedItems` property of the SheetList and DssPathList objects. Unfortunately no `SelectedItems` property exists when attempting to data bind in XAML. Is there a way of doing this in XAML and not in the code-behind?

https://github.com/HydrologicEngineeringCenter/DSSExcelPlugin/blob/44bdbeda60739d68ad068ae7bf7f941a8cd116f8/DSSExcel/MainWindow.xaml#L27-L28

https://github.com/HydrologicEngineeringCenter/DSSExcelPlugin/blob/44bdbeda60739d68ad068ae7bf7f941a8cd116f8/DSSExcel/MainWindow.xaml.cs#L121-L122

**Comment by HenryGeorgist** [comment]
https://stackoverflow.com/questions/11142976/how-to-support-listbox-selecteditems-binding-with-mvvm-in-a-navigable-applicatio
I think there is a solution by Rachel that should work for you. you might want to look at the immediately following solution by Mifeet

**Comment by HenryGeorgist** [comment]
There might be other ways to solve this problem, but if that one up above works, let me know. If it doesn't we can talk about redesigning your vm to be a bit more powerful with a dependency property.

**Comment by HenryGeorgist** [comment]
In order to implement the solution above sheets and paths might need to become something more than string lists, they might need to be an object with "isSelected" and the path as a string.  This might also cause problems with the fact that you are using a simple list and not an observable collection

**Comment by ktarbet** [comment]
I've done a major refactoring, so closing this issue for now since it may no longer apply.
