### ISSUE TITLE
Handling small index column errors in excel sheets

### ISSUE THREAD

**Issue by neemanejad** [HydrologicEngineeringCenter/DSSExcel#2]
Currently, if an excel sheet has an index column and it has a numbering issue, DSSExcel will think that the excel sheet doesn't have an index column, which causes problems later during runtime since indexing the excel sheet itself will be off. There needs to be some way of accepting small numbering errors in the index column and still identify that an index column exists. 

https://github.com/HydrologicEngineeringCenter/DSSExcelPlugin/blob/2da24c3445b70ededa3add3aa61b7635df349311/DSSExcelPlugin/ExcelTools.cs#L187-L206

**Comment by ktarbet** [comment]
The latest update is using a new convention that the index column must exist, but the actual values in the index are not important.
